### ISSUE TITLE
no notifications

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/deepin-wm-switcher#1]
Since the update to **deepin-wm-switcher 1.0.2** I get no more notifications when switching wm with Alt+Tab

**Comment by fasheng** [comment]
I'm not sure this, you mean swiching windows with Alt-Tab or switching wm with Super-Tab?
But both them will not popup notifications here...

**Comment by oberon-manjaro** [comment]
I mean switching between metacity and gala/mutter with Super+Tab, yes :)
There used to be a screen message saying "window effects enabled/disabled" or something similar. This has disappeared with the update.

**Comment by fasheng** [comment]
@hualet Is it a bug or the wm swithing OSD notification has been disabled before?

**Comment by hualet** [comment]
It's definitely a new bug. Let me see if I can fix this for @sonald  :smiley:

**Comment by hualet** [comment]
I submitted a commit, it's still in code review. https://cr.deepin.io/12827 @oberon2007 @fasheng

**Comment by fasheng** [comment]
@hualet You could paste the URL of current issue so that once the code submitted the issue will be closed automatically :)

**Comment by sonald** [comment]
merged

**Comment by hualet** [comment]
@fasheng  OK, I don't even know the trick :joy: , thanks

**Comment by oberon-manjaro** [comment]
Thanks you @hualet , the fix has arrived :+1: 
Can we have an updated package please, @felixonmars ?

**Comment by hualet** [comment]
Don't worry, @oberon2007 There'll be new tags pushed tomorrow, @felixonmars will do his job 😂

**Comment by oberon-manjaro** [comment]
Ah, ok, sorry :laughing:
I'm not worrying since I've pushed a manjaro overlay package meanwhile :wink:
Thank you all! :smile:

Am 19. Mai 2016 15:46:47 MESZ, schrieb hualet notifications@github.com:

> Don't worry, @oberon2007 There'll be new tags pushed tomorrow,
> @felixonmars will do his job 😂 
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxdeepin/deepin-wm-switcher/issues/1#issuecomment-220328877

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
